=== DanielaConte/qborrow/src/test/resources/test.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.qborrow.org/test" xmlns:tns="http://www.qborrow.org/test" elementFormDefault="qualified">

    <complexType name="soggetto">
    	<sequence>
    		<element name="username" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="mail" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="ragioneSociale" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="nome" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="cognome" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="immagine" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="dataUltimaModifica" type="date" maxOccurs="1" minOccurs="0"></element>
    	</sequence>
    </complexType>
    

    <element name="soggetto" type="tns:soggetto"></element>
    
    <complexType name="oggetto">
    	<sequence>
    		<element name="id" type="int" maxOccurs="1" minOccurs="1"></element>
    		<element name="proprietario" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="titolo" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="descrizione" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="immagine" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="categoria" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="dataUltimaModifica" type="date" maxOccurs="1"
    			minOccurs="0">
    		</element>
    	</sequence>
    </complexType>

    <element name="oggetto" type="tns:oggetto"></element>
    
    <complexType name="prestiti">
    	<sequence>
    		<element name="beneficiario" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="oggettoPrestato" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="dataPrestitio" type="date" maxOccurs="1" minOccurs="0"></element>
    		<element name="dataScadenza" type="date" maxOccurs="1" minOccurs="0"></element>
    	</sequence>
    </complexType>

    <element name="prestiti" type="tns:prestiti"></element>

    <complexType name="qborrow">
    	<sequence>
    		<element name="oggetto" type="tns:oggetto" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="soggetto" type="tns:soggetto" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="prestito" type="tns:prestiti" maxOccurs="1"
    			minOccurs="0">
    		</element>
    	</sequence>
    </complexType>

    <element name="qborrow" type="tns:qborrow"></element>
</schema>

=== DanielaConte/qborrow/src/test/resources/dati.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:qborrow xmlns:tns="http://www.qborrow.org/test" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.qborrow.org/test test.xsd">
	
	<tns:oggetto>
		<tns:id>25</tns:id>
		<tns:proprietario>utente</tns:proprietario>
		<tns:titolo>raccoglitore</tns:titolo>
		<tns:immagine>percorso23</tns:immagine>
		<tns:categoria>Ufficio</tns:categoria>
		<tns:dataUltimaModifica>2017-10-16</tns:dataUltimaModifica>
	</tns:oggetto>
	
	<tns:soggetto>
		<tns:username>daniela</tns:username>
		<tns:mail>daniela@gmail.com</tns:mail>
		<tns:ragioneSociale>nd</tns:ragioneSociale>
		<tns:nome>Daniela</tns:nome>
		<tns:cognome>Conte</tns:cognome>
		<tns:immagine>C:\\percorsoFake</tns:immagine>
		<tns:dataUltimaModifica>2017-10-12</tns:dataUltimaModifica>
	</tns:soggetto>
	
</tns:qborrow>
